version: '3.8'

services: 
  web:
    image: nginx:alpine
    restart: always
    ports:
      - 81:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/

    networks:
      - nginx-php
    

  php:
    image: php:8.0-fpm
    restart: always
    volumes:
      - ./:/var/www
    networks:
      - nginx-php

networks:
  nginx-php:
    driver: bridge
